kaminariを使ったpaginationの課題提出です。
fugakkbn/fjord-books_app pull request #2
Opened 2021-03-14 15:14 UTC by FUGA0618

レビューよろしくお願いいたします！

2021-03-17 14:18 UTC, komagata requested changes

2021-03-17 14:18 UTC, komagata commented on config/locales/translation_ja.yml
> +      last: 最後  #g
ファイルの末尾に改行がないようです。エディターの設定で自動的に入るようにできるので試してみてください〜

2021-03-20 09:15 UTC, FUGA0618 commented on config/locales/translation_ja.yml
> +      last: 最後  #g
初歩的なところをすみません。。
改行を追加し、エディターの設定も変更しました。

2021-03-20 18:33 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-20 18:33 UTC, komagata commented on db/seeds.rb
> +70.times do |n|
seedを用意してあるのはいいですね！

2021-03-21 01:53 UTC, FUGA0618 commented on db/seeds.rb
> +70.times do |n|
ありがとうございます🙏

2021-03-21 01:53 UTC, merged