ユーザーフォロー機能の課題提出です。
fugakkbn/fjord-books_app pull request #6
Opened 2021-04-17 12:03 UTC by FUGA0618

レビューよろしくお願いいたします🙏

2021-04-22 01:16 UTC, komagata requested changes

2021-04-22 01:16 UTC, komagata commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
Relationshipと言う名前は全ての関連に当てはまるので他の名前がいいかもです。
（次に別の関連が出てきた時名前づけに困るため）

2021-04-22 01:16 UTC, komagata commented on app/controllers/users/followings_controller.rb
> +    @following_users = User.find(params[:user_id]).followings.with_attached_avatar.page(params[:page]).per(10)
10の部分がマジックナンバーになっているのでkaminariの機能で設定するか、定数を使いたいですね。

[マジックナンバー \(プログラム\) \- Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%B8%E3%83%83%E3%82%AF%E3%83%8A%E3%83%B3%E3%83%90%E3%83%BC_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0))

2021-04-22 12:31 UTC, FUGA0618 commented on app/controllers/users/followings_controller.rb
> +    @following_users = User.find(params[:user_id]).followings.with_attached_avatar.page(params[:page]).per(10)
kaminariの機能でモデルのデフォルト値を変更しようと考えましたが、どちらもUserモデルのため、そこを変更するとユーザー一覧にも影響が出てしまいました。
なので、それぞれ定数にしました。

2021-04-22 13:13 UTC, FUGA0618 commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
確かにこれだと、なんの関係性なのかわかりづらいですね…！
FollowRelationshipという名前に変えてみましたがいかがでしょうか。

2021-04-23 16:22 UTC, komagata commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
全ての関連に〜Relationshipとつけるわけにもいかないので、例えばFriendshipとか他の単語を使いたいですね〜

2021-04-25 09:22 UTC, FUGA0618 commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
Friendshipの方が簡潔かつわかりやすいですね…！
変更しました。

2021-04-26 08:20 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-26 08:20 UTC, komagata commented on app/controllers/friendships_controller.rb
> +class FriendshipsController < ApplicationController
👍

2021-04-26 08:20 UTC, komagata commented on app/controllers/users/followers_controller.rb
> +  PAGINATES_PER = 10
👍

2021-04-27 10:11 UTC, merged